services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=goop
      - MYSQL_DATABASE=pluribus
      - MYSQL_USER=pluribus-web
      - MYSQL_PASSWORD=pluribus-web

  mail: # view email ui at http://localhost:8025
    image: axllent/mailpit:latest
    container_name: mail
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - MYSQL_ROOT_PASSWORD=goop
    depends_on:
      - db
      
  phpmyadmin-prod:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-prod
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=host.docker.internal
      - PMA_PORT=3307
      - MYSQL_ROOT_PASSWORD=pluribus-w3b
    volumes:
      - /run/mysqld/mysqld.sock:/run/mysqld/mysqld.sock
    