services:
  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=goop
      - MYSQL_DATABASE=pluribus
      - MYSQL_USER=pluribus-web
      - MYSQL_PASSWORD=pluribus-web

  mail: # view email ui at http://localhost:8025
    image: axllent/mailpit:latest
    container_name: mail
    restart: always
    ports:
      - "8025:8025"
      - "1025:1025"
    